DROP TABLE KHOAHOC CASCADE CONSTRAINT;
DROP TABLE CHUONGTRINH CASCADE CONSTRAINT;
DROP TABLE LOAILOP CASCADE CONSTRAINT;
DROP TABLE LOP CASCADE CONSTRAINT;
DROP TABLE HOCVIEN CASCADE CONSTRAINT;
DROP TABLE PHIEUTHU CASCADE CONSTRAINT;
DROP TABLE MONHOC CASCADE CONSTRAINT;
DROP TABLE DIEM CASCADE CONSTRAINT;